// Mocks generated by Mockito 5.4.6 from annotations
// in taxi_booking/test/core/data/sources/mock_remote_data_source.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:taxi_booking/core/data/models/base_response_model.dart' as _i2;
import 'package:taxi_booking/core/domain/services/RemoteDataSource.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseResponseModel_0 extends _i1.SmartFake
    implements _i2.BaseResponseModel {
  _FakeBaseResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponseModel> get(
    String? path, {
    Map<String, dynamic>? queryParams,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParams: queryParams, #cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParams: queryParams, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<_i2.BaseResponseModel> post(
    String? path, {
    dynamic queryParams,
    dynamic body,
    _i5.FormData? formData,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #queryParams: queryParams,
                #body: body,
                #formData: formData,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #queryParams: queryParams,
                    #body: body,
                    #formData: formData,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<_i2.BaseResponseModel> patch(
    String? path, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
    _i5.FormData? formData,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #queryParams: queryParams,
                #body: body,
                #formData: formData,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #queryParams: queryParams,
                    #body: body,
                    #formData: formData,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<_i2.BaseResponseModel> postFiles(
    String? path, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
    _i5.FormData? formData,
    String? key,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postFiles,
              [path],
              {
                #queryParams: queryParams,
                #body: body,
                #formData: formData,
                #key: key,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #postFiles,
                  [path],
                  {
                    #queryParams: queryParams,
                    #body: body,
                    #formData: formData,
                    #key: key,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<_i2.BaseResponseModel> postList(
    String? path, {
    Map<String, dynamic>? queryParams,
    List<dynamic>? body,
    _i5.FormData? formData,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postList,
              [path],
              {
                #queryParams: queryParams,
                #body: body,
                #formData: formData,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #postList,
                  [path],
                  {
                    #queryParams: queryParams,
                    #body: body,
                    #formData: formData,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<dynamic> downloadFile(
    _i6.BuildContext? context,
    String? path,
    String? savePath,
    int? fileId, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
    _i5.FormData? formData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [context, path, savePath, fileId],
              {#queryParams: queryParams, #body: body, #formData: formData},
            ),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<_i2.BaseResponseModel> put(
    String? path, {
    Map<String, dynamic>? queryParams,
    dynamic body,
    _i5.FormData? formData,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #queryParams: queryParams,
                #body: body,
                #formData: formData,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #queryParams: queryParams,
                    #body: body,
                    #formData: formData,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<_i2.BaseResponseModel> delete(
    String? path, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #queryParams: queryParams,
                #body: body,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.BaseResponseModel>.value(
              _FakeBaseResponseModel_0(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #queryParams: queryParams,
                    #body: body,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponseModel>);

  @override
  _i4.Future<void> downloadFileWeb(
    String? url,
    String? fileName, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFileWeb,
              [url, fileName],
              {#queryParams: queryParams},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
